-- 코드를 입력하세요
select a.member_name,b.review_text,to_char(b.review_date,'YYYY-MM-DD') AS REVIEW_DATE
FROM MEMBER_PROFILE A,REST_REVIEW B
WHERE A.MEMBER_ID = B.MEMBER_ID AND A.MEMBER_ID IN
(SELECT MEMBER_ID
FROM REST_REVIEW
GROUP BY MEMBER_ID
HAVING COUNT(*) = (
        SELECT MAX(REVIEW_COUNT)
        FROM (
                SELECT MEMBER_ID, COUNT(*) AS REVIEW_COUNT
                FROM REST_REVIEW
                GROUP BY MEMBER_ID
)))
ORDER BY B.REVIEW_DATE ASC ,B.REVIEW_TEXT ASC
;