SELECT A.MEMBER_NAME, B.REVIEW_TEXT,date_format(B.REVIEW_DATE,'%Y-%m-%d') as REVIEW_DATE
FROM MEMBER_PROFILE AS A 
INNER JOIN REST_REVIEW AS B
ON A.MEMBER_ID = B.MEMBER_ID
WHERE A.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM (
        SELECT MEMBER_ID, COUNT(*) AS COUNT_REVIEW
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
    ) subquery
    WHERE COUNT_REVIEW = (
        SELECT MAX(COUNT_REVIEW)
        FROM (
            SELECT MEMBER_ID, COUNT(*) AS COUNT_REVIEW
            FROM REST_REVIEW
            GROUP BY MEMBER_ID
        ) inner_subquery
    )
)
ORDER BY B.REVIEW_DATE ASC, B.REVIEW_TEXT ASC;